#!/usr/bin/env bash
# bootstrap.sh - runs ON a RunPod pod. Installs tmux, node, Claude Code, Codex, uv.
# Everything stateful lives on /workspace so it survives pod stop/start.
# Idempotent: safe to re-run. Re-run after every pod restart (the container disk,
# including apt packages and ~/.bashrc, is wiped; /workspace is not).
#
# Usage: bootstrap.sh [--update]
#   --update  also update Claude Code, Codex and uv to their latest versions
set -euo pipefail

WS=/workspace
PHOME=$WS/home            # persistent "home": configs, auth, dotfiles
TOOLS=$WS/tools           # runtimes (node)
BIN=$WS/bin               # standalone binaries (uv, ...)
NPM_PREFIX=$WS/npm-global # npm global installs (claude, codex)
ENVFILE=$WS/pod_env.sh

UPDATE=0
for a in "$@"; do
  case $a in
    --update) UPDATE=1 ;;
  esac
done

log() { printf '\033[1;34m[bootstrap]\033[0m %s\n' "$*"; }

[ -d "$WS" ] || { echo "ERROR: /workspace not found. Is this a RunPod pod with a volume?" >&2; exit 1; }

mkdir -p "$PHOME" "$TOOLS" "$BIN" "$NPM_PREFIX" \
         "$PHOME/.claude" "$PHOME/.codex" "$PHOME/.config/tmux" \
         "$PHOME/.local/share" \
         "$WS/cache/pip" "$WS/cache/uv" "$WS/cache/huggingface"
chmod 700 "$PHOME/.claude" "$PHOME/.codex"

# ---------- apt packages (container disk, cheap to reinstall on each restart) ----------
if command -v apt-get >/dev/null 2>&1; then
  export DEBIAN_FRONTEND=noninteractive
  missing=""
  for p in tmux git curl ca-certificates xz-utils ripgrep htop less unzip vim procps; do
    dpkg -s "$p" >/dev/null 2>&1 || missing="$missing $p"
  done
  if [ -n "$missing" ]; then
    log "installing apt packages:$missing"
    apt-get update -qq
    # shellcheck disable=SC2086
    apt-get install -y -qq --no-install-recommends $missing >/dev/null
  else
    log "apt packages already installed"
  fi
else
  log "WARNING: apt-get not found, skipping system packages (tmux may be missing)"
fi

# ---------- node (persistent, on /workspace) ----------
case "$(uname -m)" in
  x86_64) NARCH=x64 ;;
  aarch64|arm64) NARCH=arm64 ;;
  *) echo "ERROR: unsupported architecture $(uname -m)" >&2; exit 1 ;;
esac

NODE_VERSION=${NODE_VERSION:-}
if [ -z "$NODE_VERSION" ]; then
  NODE_VERSION=$(curl -fsSL https://nodejs.org/dist/latest-v22.x/ 2>/dev/null \
    | grep -oE 'node-v22\.[0-9]+\.[0-9]+' | head -1 | cut -c7- || true)
  NODE_VERSION=${NODE_VERSION:-22.17.1}
fi

NODE_DIR=$TOOLS/node-v$NODE_VERSION-linux-$NARCH
if [ ! -x "$NODE_DIR/bin/node" ]; then
  log "installing node v$NODE_VERSION"
  # extract to a temp dir first so a failed install can't leave a partial NODE_DIR;
  # --no-same-owner because network volumes like /workspace refuse chown
  rm -rf "$NODE_DIR" "$TOOLS/.node-tmp"
  mkdir -p "$TOOLS/.node-tmp"
  curl -fsSL "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-$NARCH.tar.xz" \
    | tar -xJ --no-same-owner -C "$TOOLS/.node-tmp"
  mv "$TOOLS/.node-tmp/node-v$NODE_VERSION-linux-$NARCH" "$NODE_DIR"
  rmdir "$TOOLS/.node-tmp"
else
  log "node v$NODE_VERSION already installed"
fi
ln -sfn "$NODE_DIR" "$TOOLS/node"

export NPM_CONFIG_PREFIX=$NPM_PREFIX
export PATH="$PHOME/.local/bin:$TOOLS/node/bin:$NPM_PREFIX/bin:$BIN:$PATH"

# ---------- Claude Code (official native installer, persistent via HOME override) ----------
# Installed with HOME=$PHOME so the binary and its self-updates land on /workspace.
# (Codex's native installer can't do this: its tar step dies on the network
# volume's chown restriction, so codex comes from npm below.)
if [ ! -x "$PHOME/.local/bin/claude" ] || [ "$UPDATE" = 1 ]; then
  log "installing claude (native installer)"
  HOME=$PHOME bash -c 'curl -fsSL https://claude.ai/install.sh | bash' >/dev/null
else
  log "claude already installed"
fi
# drop any npm-installed copy so it can't shadow the native one
[ -e "$NPM_PREFIX/bin/claude" ] && npm uninstall -g --silent @anthropic-ai/claude-code >/dev/null 2>&1 || true

if [ ! -x "$NPM_PREFIX/bin/codex" ] || [ "$UPDATE" = 1 ]; then
  log "installing @openai/codex"
  npm install -g --silent @openai/codex
else
  log "codex already installed"
fi

# ---------- uv (persistent binary on /workspace) ----------
if [ ! -x "$BIN/uv" ] || [ "$UPDATE" = 1 ]; then
  log "installing uv"
  curl -LsSf https://astral.sh/uv/install.sh \
    | env UV_INSTALL_DIR="$BIN" UV_NO_MODIFY_PATH=1 sh >/dev/null
else
  log "uv already installed"
fi

# ---------- environment file, sourced by every shell ----------
# Regenerated on every bootstrap run; put personal additions in /workspace/pod_env.local.sh
cat > "$ENVFILE" <<'EOF'
# Generated by bootstrap.sh. Do not edit; use /workspace/pod_env.local.sh for additions.
export WS=/workspace
case ":$PATH:" in
  *:/workspace/bin:*) ;;
  *) export PATH="/workspace/home/.local/bin:/workspace/tools/node/bin:/workspace/npm-global/bin:/workspace/bin:$PATH" ;;
esac
export NPM_CONFIG_PREFIX=/workspace/npm-global
export CLAUDE_CONFIG_DIR=/workspace/home/.claude
export CODEX_HOME=/workspace/home/.codex
export GIT_CONFIG_GLOBAL=/workspace/home/.gitconfig
export XDG_CONFIG_HOME=/workspace/home/.config
export XDG_DATA_HOME=/workspace/home/.local/share
export XDG_CACHE_HOME=/workspace/cache
export HF_HOME=/workspace/cache/huggingface
export PIP_CACHE_DIR=/workspace/cache/pip
export UV_CACHE_DIR=/workspace/cache/uv
export HISTFILE=/workspace/home/.bash_history
export EDITOR=vim
alias ws='cd /workspace'
[ -f /workspace/pod_env.local.sh ] && . /workspace/pod_env.local.sh
EOF

# ---------- hook the env file into shell startup (container disk, redo each restart) ----------
# Two hooks in ~/.bashrc:
#  - early (line 1): non-interactive ssh shells hit Ubuntu's interactive guard and
#    return before the end of the file, so only a top-of-file hook reaches them
#  - late (last line): RunPod's start script appends "source /etc/rp_environment"
#    to .bashrc, which re-exports a fixed PATH snapshot and would clobber the
#    early hook in interactive shells; the late hook runs after it and wins
log "hooking pod_env.sh into shell startup files"
HOOK='[ -f /workspace/pod_env.sh ] && . /workspace/pod_env.sh'
BRC=$HOME/.bashrc
touch "$BRC"
sed -i '\%^\[ -f /workspace/pod_env\.sh \]%d' "$BRC"
{ echo "$HOOK # pod-env-early"; cat "$BRC"; } > "$BRC.new"
mv "$BRC.new" "$BRC"
echo "$HOOK # pod-env-late" >> "$BRC"
# system-wide, for interactive shells whose HOME is not $HOME (e.g. web terminals)
if [ -f /etc/bash.bashrc ] && ! grep -q 'pod_env.sh' /etc/bash.bashrc; then
  echo "$HOOK # pod-env" >> /etc/bash.bashrc
fi
# login shells of any user
mkdir -p /etc/profile.d
echo "$HOOK" > /etc/profile.d/pod-env.sh

# ---------- default tmux config (persistent, only written if absent) ----------
TMUX_CONF=$PHOME/.config/tmux/tmux.conf
if [ ! -f "$TMUX_CONF" ]; then
  log "writing default tmux config"
  cat > "$TMUX_CONF" <<'EOF'
set -g mouse on
set -g history-limit 100000
set -g default-terminal "screen-256color"
set -sg escape-time 10
setw -g mode-keys vi
EOF
fi

# ---------- summary ----------
log "versions:"
echo "    node   $(node -v)"
echo "    npm    $(npm -v)"
echo "    tmux   $(tmux -V 2>/dev/null || echo 'NOT INSTALLED')"
echo "    claude $(claude --version 2>/dev/null || echo 'NOT INSTALLED')"
echo "    codex  $(codex --version 2>/dev/null || echo 'NOT INSTALLED')"
echo "    uv     $(uv --version 2>/dev/null || echo 'NOT INSTALLED')"
log "bootstrap complete"
